In [4]:
#Import the Library
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd
import numpy as np

### Read CSV data

In [8]:
df = pd.read_csv('Lottery_data.csv')
df['result']=1
df.head()

id  first  second  third  fourth  fifth  Yellow  result
0   1      1       4      6      11     14      30       1
1   2      1      10     13      19     21      28       1
2   3      1      10     13      19     21      28       1
3   4      1      16     18      25     27       3       1
4   5      1       2     13      19     27      21       1

## Create Random FALSE numbers

In [9]:
import random
first= []
second=[]
third=[]
fourth=[]
fifth=[]
sixth=[]
result=[]

for x in range(1000):
    first.append(random.randint(1,70))
    second.append(random.randint(1,70))
    third.append(random.randint(1,70))
    fourth.append(random.randint(1,70))
    fifth.append(random.randint(1,70))
    sixth.append(random.randint(1,25))
    result.append(0)

## Create dataframe for the losing numbers

In [10]:
df_loser= pd.DataFrame({'first':first,
                       'second':second,
                       'third':third,
                        'fourth':fourth,
                        'fifth':fifth,
                        'Yellow':sixth,
                        'result':result
                       }) 

### Concatinate the winning numbers with loosing ones


In [11]:
frames=[df,df_loser]
result = pd.concat(frames)

In [12]:
result.head()

Yellow  fifth  first  fourth   id  result  second  third
0      30     14      1      11  1.0       1       4      6
1      28     21      1      19  2.0       1      10     13
2      28     21      1      19  3.0       1      10     13
3       3     27      1      25  4.0       1      16     18
4      21     27      1      19  5.0       1       2     13

## Bulid a machine learning model RANDOM FOREST 

In [13]:
#Import Random Forest Classifier from SKLEARN library
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100, criterion='entropy',max_depth=10,random_state=0)

In [14]:
# Spilt and train the data
from sklearn.model_selection import train_test_split
X=result[['first','second','third','fourth','fifth','Yellow']]
Y= result['result']

x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2, random_state=42)

# Normalizing the data values
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [15]:
# Fit the data into the model
clf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [16]:
#Predict the outcome
y_predict = clf.predict(x_test)

In [18]:
# measuring the results by condusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_predict)
print(cm)

[[186  10]
 [  4 206]]


In [19]:
#model score and accuracy
clf.score(x_test,y_test)

0.9655172413793104

## Predicting the winning numbers

In [259]:
import random
process = False
while process is False:
    first_nu =random.sample(range(1,70), 5)
    sixth_nu = random.randint(1,25)
    numbers = first_nu + [sixth_nu]
    re = clf.predict([numbers])
    if re == 1:
        
        print (f'Your winning numbers are: {numbers}')
        process = True
    
    

Your winning numbers are: [69, 33, 3, 2, 21, 11]


### Removing and sorting predicted numbers


In [260]:
numbers.remove(numbers[5])
numbers.sort()


### Cusromer input numbers

In [264]:
first = int(input('Write your first number (1-75): '))
second = int(input('Write your second number (1-75): '))
third = int(input('Write your third number (1-75): '))
fourth = int(input('Write your fourth number (1-75): '))
fifth = int(input('Write your fifth number (1-75): '))
sixth = int(input('Write your sixth number (1-25): '))

Write your first number (1-75): 55
Write your second number (1-75): 59
Write your third number (1-75): 62
Write your fourth number (1-75): 75
Write your fifth number (1-75): 74
Write your sixth number (1-25): 2


### Sorting the numbers 

In [265]:
numbers = [first, second, third, fourth, fifth]
numbers.sort()
numbers.append(sixth)

In [266]:
numbers

[55, 59, 62, 74, 75, 2]

In [ ]:
predict_results(numbers)


### Predict function for the typed or generated numbers

In [159]:
def predict_results(numbers):
    
    # Calculate the total probability of the numbers
    prob_total = dff[dff['numbers'] == numbers[0]]['prob_1'].values *dff[dff['numbers'] == numbers[1]]['prob_2'].values*dff[dff['numbers'] == numbers[2]]['prob_3'].values *dff[dff['numbers'] == numbers[3]]['prob_4'].values *dff[dff['numbers'] ==numbers[4]]['prob_5'].values 
    
    # Results classification list
    range_result = ['very rare','rare','average','good','very good','highly possible','highly recommended']
    
    # Classify the results based on the total probabilities outcome
    if prob_total <= 1e-7 and prob_total > 1e-10:
        print (range_result[6])
    elif prob_total <= 1e-10 and prob_total > 1e-11:
        print (range_result[5])
    elif prob_total <= 1e-11 and prob_total > 1e-12:
        print (range_result[4])
    elif prob_total <= 1e-12 and prob_total > 1e-13:
        print (range_result[3])
    elif prob_total <= 1e-13 and prob_total > 1e-14:
        print (range_result[2])
    elif prob_total <= 1e-14 and prob_total > 1e-15:
        print (range_result[1])
    elif prob_total <= 1e-15:
        print (range_result[0])
        
    


In [267]:
predict_results(numbers)


very rare


In [121]:
dff[dff['numbers'] == 5]['prob_1'].values *dff[dff['numbers'] == 6]['prob_2'].values*dff[dff['numbers'] == 20]['prob_3'].values *dff[dff['numbers'] == 65]['prob_4'].values *dff[dff['numbers'] ==70]['prob_5'].values 

array([1.89766097e-08])

In [136]:

f= dff[dff['numbers'] == 2]['prob_1'].values *dff[dff['numbers'] == 15]['prob_2'].values*dff[dff['numbers'] == 31]['prob_3'].values *dff[dff['numbers'] == 46]['prob_4'].values *dff[dff['numbers'] ==53]['prob_5'].values 

In [137]:
float(f)

2.391784201483983e-07

In [134]:

e= dff[dff['numbers'] == 46]['prob_1'].values *dff[dff['numbers'] == 47]['prob_2'].values*dff[dff['numbers'] == 67]['prob_3'].values *dff[dff['numbers'] == 72]['prob_4'].values *dff[dff['numbers'] ==33]['prob_5'].values 

In [135]:
e

array([2.61310176e-15])

In [138]:
range_result = ['very rare','rare','low average','in average','above average','good','very good','highly possible','highly recommended']

In [139]:
range_result

['very rare',
 'rare',
 'low average',
 'in average',
 'above average',
 'good',
 'very good',
 'highly possible',
 'highly recommended']

In [143]:
dff[dff['numbers'] == 29]['prob_1'].values *dff[dff['numbers'] == 52]['prob_2'].values*dff[dff['numbers'] == 58]['prob_3'].values *dff[dff['numbers'] == 60]['prob_4'].values *dff[dff['numbers'] ==62]['prob_5'].values 

array([0.])

### Classify the numbers